    setlocale(LC_ALL,"en_US.UTF-8");
    wchar_t str1[] = L"Привет";
    printf("str1 = %S\n", str1);
    printf("sizeof str1 = %lu\n", sizeof(str1));
    char str2[] = "Привет";
    printf("str2 = %s\n",str2);
    printf("sizeof str2 = %lu\n", sizeof(str2));
    char str3[] = "Hello!";
    printf("str3 = %s\n",str3);
    printf("sizeof str3 = %lu\n", sizeof(str3));